import time
import re

SCHEMES = [
    {
        "id": "pm-kisan",
        "name": "PM-KISAN Scheme",
        "name_ta": "பிரதமர் கிசான் திட்டம்",
        "category": "central_finance",
        "category_en": "Central Government Financial",
        "category_ta": "மத்திய அரசு நிதி திட்டங்கள்",
        "department": "Ministry of Agriculture & Farmers Welfare",
        "department_ta": "விவசாயம் மற்றும் விவசாயிகள் நல அமைச்சகம்",
        "benefits": "Annual financial benefit of Rs. 6000 transferred directly to bank accounts in three equal installments of Rs. 2000 each.",
        "benefits_ta": "ஆண்டுக்கு ரூ. 6000 நிதி உதவி நேரடியாக வங்கி கணக்கில் மூன்று சம தவணைகளில் (தலா ரூ. 2000) வழங்கப்படுகிறது.",
        "eligibility": "All landholding farmer families with cultivable land. Excludes institutional land holders, former/present constitutional office holders.",
        "eligibility_ta": "சாகுபடி நிலம் கொண்ட அனைத்து விவசாயி குடும்பங்கள். நிறுவன நிலம் வைத்திருப்பவர்கள், அரசியல் சாசன பதவி வகிப்போர் தவிர்க்கப்பட்டுள்ளனர்.",
        "documents": "Aadhaar Card, Land Records, Bank Account Details, Farmer ID",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், வங்கி கணக்கு விவரங்கள், விவசாயி அடையாள அட்டை",
        "link": "https://pmkisan.gov.in",
        "icon": "💰",
        "is_featured": True,
        "deadline": "",
    },
    {
        "id": "pmfby",
        "name": "Pradhan Mantri Fasal Bima Yojana",
        "name_ta": "பிரதமர் பயிர் காப்பீட்டு திட்டம்",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "மத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Ministry of Agriculture & Farmers Welfare",
        "department_ta": "விவசாயம் மற்றும் விவசாயிகள் நல அமைச்சகம்",
        "benefits": "Comprehensive crop insurance covering natural calamities, pests, diseases. Low premium of 1.5-5% with balance subsidized by government.",
        "benefits_ta": "இயற்கை பேரிடர்கள், பூச்சிகள், நோய்களுக்கு எதிரான விரிவான பயிர் காப்பீடு. 1.5-5% குறைந்த பிரீமியம், மீதி அரசு மானியம்.",
        "eligibility": "All farmers growing notified crops in notified areas. Includes loanee and non-loanee farmers.",
        "eligibility_ta": "அறிவிக்கப்பட்ட பகுதிகளில் அறிவிக்கப்பட்ட பயிர்களை பயிரிடும் அனைத்து விவசாயிகள். கடன் பெற்ற மற்றும் கடன் பெறாத விவசாயிகள்.",
        "documents": "Aadhaar Card, Land Records, Bank Account Details, Crop Details",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், வங்கி கணக்கு விவரங்கள், பயிர் விவரங்கள்",
        "link": "https://pmfby.gov.in",
        "icon": "🛡️",
        "is_featured": True,
        "deadline": "31st July (Kharif), 31st December (Rabi)",
    },
    {
        "id": "enam",
        "name": "National Agriculture Market (e-NAM)",
        "name_ta": "தேசிய வேளாண் சந்தை (இ-நாம்)",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "மத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Ministry of Agriculture & Farmers Welfare",
        "department_ta": "விவசாயம் மற்றும் விவசாயிகள் நல அமைச்சகம்",
        "benefits": "Online trading platform for better price discovery. Farmers can sell produce remotely, get transparent pricing, and direct payment.",
        "benefits_ta": "சிறந்த விலை கண்டுபிடிப்புக்கான ஆன்லைன் வர்த்தக தளம். விவசாயிகள் தொலைதூரத்தில் இருந்தே விற்கலாம், வெளிப்படையான விலை மற்றும் நேரடி கட்டணம் பெறலாம்.",
        "eligibility": "All farmers registered with APMC. Free registration for farmers.",
        "eligibility_ta": "APMC-யில் பதிவு செய்த அனைத்து விவசாயிகள். விவசாயிகளுக்கு இலவச பதிவு.",
        "documents": "Aadhaar Card, Bank Account, Mobile Number, Land Records",
        "documents_ta": "ஆதார் அட்டை, வங்கி கணக்கு, கைப்பேசி எண், நில ஆவணங்கள்",
        "link": "https://www.enam.gov.in",
        "icon": "📱",
        "is_featured": True,
        "deadline": "",
    },
    {
        "id": "soil-health-card",
        "name": "Soil Health Card Scheme",
        "name_ta": "மண் ஆரோக்கிய அட்டை திட்டம்",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "மத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Department of Agriculture & Farmers Welfare",
        "department_ta": "விவசாயம் மற்றும் விவசாயிகள் நல துறை",
        "benefits": "Free soil testing every 3 years. Provides customized fertilizer recommendations based on soil nutrient status.",
        "benefits_ta": "ஒவ்வொரு 3 வருடங்களுக்கும் இலவச மண் பரிசோதனை. மண்ணின் சத்து நிலை அடிப்படையில் தனிப்பயனாக்கப்பட்ட உர பரிந்துரைகள்.",
        "eligibility": "All farmers with cultivable land.",
        "eligibility_ta": "சாகுபடி நிலம் கொண்ட அனைத்து விவசாயிகள்.",
        "documents": "Land Records, Farmer ID, Aadhaar Card",
        "documents_ta": "நில ஆவணங்கள், விவசாயி அடையாள அட்டை, ஆதார் அட்டை",
        "link": "https://soilhealth.dac.gov.in",
        "icon": "🧪",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "pmksy",
        "name": "Pradhan Mantri Krishi Sinchayee Yojana",
        "name_ta": "பிரதமர் வேளாண் நீர்ப்பாசன திட்டம்",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "मத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Ministry of Water Resources",
        "department_ta": "நீர் வள அமைச்சகம்",
        "benefits": "Subsidy up to 55% for micro irrigation systems (drip/sprinkler). Water conservation and efficient irrigation infrastructure.",
        "benefits_ta": "சிறு நீர்ப்பாசன முறைகளுக்கு (சொட்டு/தெளிப்பு) 55% வரை மானியம். நீர் பாதுகாப்பு மற்றும் திறமையான நீர்ப்பாசன உள்கட்டமைப்பு.",
        "eligibility": "Small and marginal farmers, all farmers with cultivable land.",
        "eligibility_ta": "சிறு மற்றும் குறு விவசாயிகள், சாகுபடி நிலம் கொண்ட அனைத்து விவசாயிகள்.",
        "documents": "Land Records, Aadhaar Card, Bank Details, Farm Plan",
        "documents_ta": "நில ஆவணங்கள், ஆதார் அட்டை, வங்கி விவரங்கள், பண்ணை திட்டம்",
        "link": "https://pmksy.gov.in",
        "icon": "💧",
        "is_featured": True,
        "deadline": "",
    },
    {
        "id": "pkvy",
        "name": "Paramparagat Krishi Vikas Yojana",
        "name_ta": "பாரம்பரிய வேளாண் வளர்ச்சி திட்டம்",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "மத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Department of Agriculture & Farmers Welfare",
        "department_ta": "वிவசாயம் மற்றும் விவசாயிகள் நல துறை",
        "benefits": "Promotes organic farming through clusters. Provides Rs. 50,000 per hectare for 3 years covering certification, inputs, and marketing.",
        "benefits_ta": "கொத்துகள் மூலம் இயற்கை விவசாயத்தை ஊக்குவிக்கிறது. சான்றிதழ், உள்ளீடுகள் மற்றும் சந்தைப்படுத்தலுக்கு 3 ஆண்டுகளுக்கு ஹெக்டேருக்கு ரூ. 50,000 மானியம்.",
        "eligibility": "Farmers willing to practice organic farming in groups/clusters.",
        "eligibility_ta": "குழுக்களாக இயற்கை விவசாயம் செய்ய விரும்பும் விவசாயிகள்.",
        "documents": "Aadhaar Card, Land Records, Organic Farm Plan, Group Registration",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், இயற்கை பண்ணை திட்டம், குழு பதிவு",
        "link": "https://pkvy.dac.gov.in",
        "icon": "🌱",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "pm-kmy",
        "name": "Pradhan Mantri Kisan Maan Dhan Yojana",
        "name_ta": "பிரதமர் கிசான் மான்தன் திட்டம்",
        "category": "central_finance",
        "category_en": "Central Government Financial",
        "category_ta": "மத்திய அரசு நிதி திட்டங்கள்",
        "department": "Ministry of Agriculture & Farmers Welfare",
        "department_ta": "விவசாயம் மற்றும் விவசாயிகள் நல அமைச்சகம்",
        "benefits": "Pension scheme for small and marginal farmers. Monthly pension of Rs. 3000 after 60 years with monthly contribution of Rs. 55-200.",
        "benefits_ta": "சிறு மற்றும் குறு விவசாயிகளுக்கான ஓய்வூதிய திட்டம். 60 வயதுக்குப் பிறகு மாதம் ரூ. 3000 ஓய்வூதியம், மாதாந்திர பங்களிப்பு ரூ. 55-200.",
        "eligibility": "Small and marginal farmers aged 18-40 years with cultivable land up to 2 hectares.",
        "eligibility_ta": "18-40 வயதுக்குட்பட்ட சிறு மற்றும் குறு விவசாயிகள், 2 ஹெக்டேர் வரை சாகுபடி நிலம்.",
        "documents": "Aadhaar Card, Land Records, Bank Account, Age Proof",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், வங்கி கணக்கு, வயது சான்று",
        "link": "https://pmkmy.gov.in",
        "icon": "👴",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "rkvy",
        "name": "Rashtriya Krishi Vikas Yojana",
        "name_ta": "தேசிய வேளாண் வளர்ச்சி திட்டம்",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "மத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Ministry of Agriculture & Farmers Welfare",
        "department_ta": "விவசாயம் மற்றும் விவசாயிகள் நல அமைச்சகம்",
        "benefits": "Holistic development of agriculture through state-specific projects. Supports infrastructure, technology adoption, and value addition.",
        "benefits_ta": "மாநிலம் சார்ந்த திட்டங்கள் மூலம் வேளாண்மையின் முழுமையான வளர்ச்சி. உள்கட்டமைப்பு, தொழில்நுட்ப தத்தெடுப்பு மற்றும் மதிப்பு கூட்டல் ஆதரவு.",
        "eligibility": "State governments, farmer groups, and individual farmers through state-level programs.",
        "eligibility_ta": "மாநில அரசுகள், விவசாயி குழுக்கள் மற்றும் தனிப்பட்ட விவசாயிகள் (மாநில அளவிலான திட்டங்கள் வழியாக).",
        "documents": "Varies by project. Typically: Aadhaar, Land Records, Project Proposal",
        "documents_ta": "திட்டத்தைப் பொறுத்து மாறுபடும். பொதுவாக: ஆதார், நில ஆவணங்கள், திட்ட முன்மொழிவு",
        "link": "https://rkvy.nic.in",
        "icon": "🏗️",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "nfsm",
        "name": "National Food Security Mission",
        "name_ta": "தேசிய உணவு பாதுகாப்பு இயக்கம்",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "மத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Department of Agriculture & Farmers Welfare",
        "department_ta": "விவசாயம் மற்றும் விவசாயிகள் நல துறை",
        "benefits": "Increases production of rice, wheat, pulses, and coarse cereals. Provides quality seeds, soil amendments, and training.",
        "benefits_ta": "நெல், கோதுமை, பயறு மற்றும் தானிய உற்பத்தியை அதிகரிக்கிறது. தரமான விதைகள், மண் சீர்திருத்தங்கள் மற்றும் பயிற்சி வழங்குகிறது.",
        "eligibility": "Farmers in identified districts growing target crops.",
        "eligibility_ta": "இலக்கு பயிர்களை பயிரிடும் அடையாளம் காணப்பட்ட மாவட்டங்களில் உள்ள விவசாயிகள்.",
        "documents": "Aadhaar Card, Land Records, Crop Details",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், பயிர் விவரங்கள்",
        "link": "https://nfsm.gov.in",
        "icon": "🌾",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "midh",
        "name": "Mission for Integrated Development of Horticulture",
        "name_ta": "தோட்டக்கலை ஒருங்கிணைந்த வளர்ச்சி இயக்கம்",
        "category": "central_agri",
        "category_en": "Central Government Agriculture",
        "category_ta": "मத்திய அரசு வேளாண் திட்டங்கள்",
        "department": "Department of Agriculture & Farmers Welfare",
        "department_ta": "वிவசாயம் மற்றும் விவசாயிகள் நல துறை",
        "benefits": "Comprehensive support for horticulture crops. Subsidy on planting material, polyhouses, shade nets, and post-harvest infrastructure.",
        "benefits_ta": "தோட்டக்கலை பயிர்களுக்கான விரிவான ஆதரவு. நடவு பொருட்கள், பாலிஹவுஸ், ஷேட்நெட் மற்றும் அறுவடைக்குப் பிந்தைய உள்கட்டமைப்புக்கு மானியம்.",
        "eligibility": "Farmers cultivating horticulture crops (fruits, vegetables, spices, flowers).",
        "eligibility_ta": "தோட்டக்கலை பயிர்கள் (பழங்கள், காய்கறிகள், மசாலா, பூக்கள்) பயிரிடும் விவசாயிகள்.",
        "documents": "Aadhaar Card, Land Records, Bank Details, Farm Plan",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், வங்கி விவரங்கள், பண்ணை திட்டம்",
        "link": "https://midh.gov.in",
        "icon": "🍎",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-free-electricity",
        "name": "Free Electricity for Farmers Scheme",
        "name_ta": "விவசாயிகளுக்கான இலவச மின்சார திட்டம்",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Electricity Board (TNEB)",
        "department_ta": "தமிழ்நாடு மின்சார வாரியம்",
        "benefits": "Free electricity supply for agricultural pump sets. No charges for connection and usage up to prescribed limits.",
        "benefits_ta": "விவசாய மோட்டார் பம்புகளுக்கு இலவச மின்சாரம். இணைப்பு மற்றும் பயன்பாட்டிற்கு கட்டணம் இல்லை (நிர்ணயிக்கப்பட்ட வரம்புகள் வரை).",
        "eligibility": "Farmers with agricultural pump sets in Tamil Nadu.",
        "eligibility_ta": "தமிழ்நாட்டில் விவசாய மோட்டார் பம்புகள் கொண்ட விவசாயிகள்.",
        "documents": "Land Records, Pump Set Details, Aadhaar Card",
        "documents_ta": "நில ஆவணங்கள், மோட்டார் பம்ப் விவரங்கள், ஆதார் அட்டை",
        "link": "https://www.tneb.in",
        "icon": "⚡",
        "is_featured": True,
        "deadline": "",
    },
    {
        "id": "tn-organic",
        "name": "Tamil Nadu Organic Farming Policy",
        "name_ta": "தமிழ்நாடு இயற்கை வேளாண் கொள்கை",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Department of Agriculture",
        "department_ta": "தமிழ்நாடு வேளாண் துறை",
        "benefits": "Subsidy for organic certification, training programs, marketing support for organic produce, and input subsidies.",
        "benefits_ta": "இயற்கை சான்றிதழுக்கு மானியம், பயிற்சி திட்டங்கள், இயற்கை விளைபொருட்களுக்கான சந்தைப்படுத்தல் ஆதரவு மற்றும் உள்ளீடு மானியங்கள்.",
        "eligibility": "Farmers willing to practice organic farming in Tamil Nadu.",
        "eligibility_ta": "தமிழ்நாட்டில் இயற்கை விவசாயம் செய்ய விரும்பும் விவசாயிகள்.",
        "documents": "Land Records, Application Form, Farm Conversion Plan",
        "documents_ta": "நில ஆவணங்கள், விண்ணப்ப படிவம், பண்ணை மாற்ற திட்டம்",
        "link": "https://www.tn.gov.in",
        "icon": "🌿",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-micro-irrigation",
        "name": "Tamil Nadu Micro Irrigation Scheme",
        "name_ta": "தமிழ்நாடு சிறு நீர்ப்பாசன திட்டம்",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Department of Agriculture",
        "department_ta": "தமிழ்நாடு வேளாண் துறை",
        "benefits": "Subsidy up to 80% on drip and sprinkler irrigation systems. Technical guidance and installation support provided.",
        "benefits_ta": "சொட்டு மற்றும் தெளிப்பு நீர்ப்பாசன முறைகளுக்கு 80% வரை மானியம். தொழில்நுட்ப வழிகாட்டுதல் மற்றும் நிறுவல் ஆதரவு.",
        "eligibility": "Small and marginal farmers in Tamil Nadu.",
        "eligibility_ta": "தமிழ்நாட்டில் உள்ள சிறு மற்றும் குறு விவசாயிகள்.",
        "documents": "Land Records, Aadhaar Card, Bank Details",
        "documents_ta": "நில ஆவணங்கள், ஆதார் அட்டை, வங்கி விவரங்கள்",
        "link": "https://www.tn.gov.in",
        "icon": "💧",
        "is_featured": True,
        "deadline": "",
    },
    {
        "id": "tn-cm-security",
        "name": "Chief Minister's Agricultural Security Scheme",
        "name_ta": "முதலமைச்சரின் வேளாண் காப்பீட்டு திட்டம்",
        "category": "tn_finance",
        "category_en": "Tamil Nadu Government Financial",
        "category_ta": "தமிழ்நாடு அரசு நிதி திட்டங்கள்",
        "department": "Tamil Nadu Department of Agriculture",
        "department_ta": "தமிழ்நாடு வேளாண் துறை",
        "benefits": "Financial assistance to farmers affected by natural calamities. Provides compensation for crop loss, input subsidies, and livelihood support.",
        "benefits_ta": "இயற்கை பேரிடர்களால் பாதிக்கப்பட்ட விவசாயிகளுக்கு நிதி உதவி. பயிர் இழப்பிற்கான இழப்பீடு, உள்ளீடு மானியங்கள் மற்றும் வாழ்வாதார ஆதரவு.",
        "eligibility": "Farmers in Tamil Nadu affected by notified natural calamities.",
        "eligibility_ta": "அறிவிக்கப்பட்ட இயற்கை பேரிடர்களால் பாதிக்கப்பட்ட தமிழ்நாட்டு விவசாயிகள்.",
        "documents": "Land Records, Crop Loss Certificate, Aadhaar Card, Bank Account",
        "documents_ta": "நில ஆவணங்கள், பயிர் இழப்பு சான்றிதழ், ஆதார் அட்டை, வங்கி கணக்கு",
        "link": "https://www.tn.gov.in",
        "icon": "🛡️",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-mechanization",
        "name": "Tamil Nadu Farm Mechanization Scheme",
        "name_ta": "தமிழ்நாடு பண்ணை இயந்திரமயமாக்கல் திட்டம்",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Department of Agriculture",
        "department_ta": "தமிழ்நாடு வேளாண் துறை",
        "benefits": "Subsidy up to 50% on farm machinery like tractors, harvesters, tillers, and power sprayers. Custom hiring centers also supported.",
        "benefits_ta": "டிராக்டர்கள், அறுவடை எந்திரங்கள், உழவு எந்திரங்கள் மற்றும் பவர் ஸ்பிரேயர்கள் போன்ற பண்ணை இயந்திரங்களுக்கு 50% வரை மானியம். கூலி வாடகை மையங்களுக்கும் ஆதரவு.",
        "eligibility": "Small, marginal, and women farmers in Tamil Nadu.",
        "eligibility_ta": "தமிழ்நாட்டில் உள்ள சிறு, குறு மற்றும் பெண் விவசாயிகள்.",
        "documents": "Aadhaar Card, Land Records, Quotation from Dealer, Bank Details",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், வியாபாரி மேற்கோள், வங்கி விவரங்கள்",
        "link": "https://www.tn.gov.in",
        "icon": "🚜",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-coconut",
        "name": "Integrated Coconut Development Scheme",
        "name_ta": "ஒருங்கிணைந்த தேங்காய் வளர்ச்சி திட்டம்",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Horticulture Department",
        "department_ta": "தமிழ்நாடு தோட்டக்கலை துறை",
        "benefits": "Subsidy for coconut plantation, intercropping, and processing units. Includes free saplings, maintenance support, and marketing assistance.",
        "benefits_ta": "தேங்காய் தோட்டம், இடைப்பயிர் மற்றும் பதப்படுத்தும் அலகுகளுக்கு மானியம். இலவச நாற்றுகள், பராமரிப்பு ஆதரவு மற்றும் சந்தை உதவி.",
        "eligibility": "Coconut farmers in Tamil Nadu.",
        "eligibility_ta": "தமிழ்நாட்டில் உள்ள தேங்காய் விவசாயிகள்.",
        "documents": "Land Records, Aadhaar Card, Farm Details",
        "documents_ta": "நில ஆவணங்கள், ஆதார் அட்டை, பண்ணை விவரங்கள்",
        "link": "https://www.tn.gov.in",
        "icon": "🥥",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-rainfed",
        "name": "Rainfed Area Development Programme",
        "name_ta": "மழைநீர் சார்ந்த பகுதி வளர்ச்சி திட்டம்",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Department of Agriculture",
        "department_ta": "தமிழ்நாடு வேளாண் துறை",
        "benefits": "Integrated farming system approach for rainfed areas. Support for water harvesting, drought management, and alternate cropping.",
        "benefits_ta": "மழைநீர் சார்ந்த பகுதிகளுக்கான ஒருங்கிணைந்த பண்ணை முறை. நீர் சேகரிப்பு, வறட்சி மேலாண்மை மற்றும் மாற்று பயிர்களுக்கு ஆதரவு.",
        "eligibility": "Farmers in rainfed areas of Tamil Nadu.",
        "eligibility_ta": "தமிழ்நாட்டின் மழைநீர் சார்ந்த பகுதிகளில் உள்ள விவசாயிகள்.",
        "documents": "Land Records, Aadhaar Card, Farm Plan",
        "documents_ta": "நில ஆவணங்கள், ஆதார் அட்டை, பண்ணை திட்டம்",
        "link": "https://www.tn.gov.in",
        "icon": "🌧️",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-solar-pump",
        "name": "Solar Powered Agricultural Pump Scheme",
        "name_ta": "சூரிய சக்தி விவசாய பம்ப் திட்டம்",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Energy Development Agency",
        "department_ta": "தமிழ்நாடு எரிசக்தி மேம்பாட்டு முகமை",
        "benefits": "Highly subsidized solar pump sets for irrigation. Reduces electricity costs and promotes renewable energy. Up to 90% subsidy available.",
        "benefits_ta": "மிகக் குறைந்த விலையில் சூரிய சக்தி பம்ப் செட்கள். மின்சார செலவை குறைக்கிறது மற்றும் புதுப்பிக்கத்தக்க எரிசக்தியை ஊக்குவிக்கிறது. 90% வரை மானியம்.",
        "eligibility": "Farmers with existing pump sets or new connections in remote/electricity-scarce areas.",
        "eligibility_ta": "தற்போதைய பம்ப் செட் கொண்ட அல்லது மின்சாரம் குறைந்த பகுதிகளில் புதிய இணைப்பு கொண்ட விவசாயிகள்.",
        "documents": "Land Records, Existing EB Connection Details, Aadhaar Card",
        "documents_ta": "நில ஆவணங்கள், தற்போதைய EB இணைப்பு விவரங்கள், ஆதார் அட்டை",
        "link": "https://www.teda.in",
        "icon": "☀️",
        "is_featured": True,
        "deadline": "",
    },
    {
        "id": "tn-dairy",
        "name": "Tamil Nadu Dairy Development Scheme",
        "name_ta": "தமிழ்நாடு பால் வளர்ச்சி திட்டம்",
        "category": "tn_finance",
        "category_en": "Tamil Nadu Government Financial",
        "category_ta": "தமிழ்நாடு அரசு நிதி திட்டங்கள்",
        "department": "Tamil Nadu Dairy Development Department",
        "department_ta": "தமிழ்நாடு பால் வளர்ச்சி துறை",
        "benefits": "Subsidy for cattle purchase, dairy equipment, and milk processing units. Free veterinary services and artificial insemination.",
        "benefits_ta": "கால்நடை கொள்முதல், பால் உபகரணங்கள் மற்றும் பால் பதப்படுத்தும் அலகுகளுக்கு மானியம். இலவச கால்நடை சிகிச்சை மற்றும் செயற்கை கருவூட்டல்.",
        "eligibility": "Small and marginal farmers, landless laborers involved in dairy farming.",
        "eligibility_ta": "சிறு மற்றும் குறு விவசாயிகள், பால் பண்ணையில் ஈடுபட்டுள்ள நிலமற்ற தொழிலாளர்கள்.",
        "documents": "Aadhaar Card, Bank Account, Cattle Details, Veterinary Certificate",
        "documents_ta": "ஆதார் அட்டை, வங்கி கணக்கு, கால்நடை விவரங்கள், கால்நடை சான்றிதழ்",
        "link": "https://www.tn.gov.in",
        "icon": "🐄",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-free-seeds",
        "name": "Free Seeds and Fertilizer Distribution Scheme",
        "name_ta": "இலவச விதை மற்றும் உர விநியோக திட்டம்",
        "category": "tn_agri",
        "category_en": "Tamil Nadu Government Agriculture",
        "category_ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்",
        "department": "Tamil Nadu Department of Agriculture",
        "department_ta": "தமிழ்நாடு வேளாண் துறை",
        "benefits": "Free distribution of quality seeds and subsidized fertilizers to farmers. Includes seed minikits for pulses and oilseeds.",
        "benefits_ta": "விவசாயிகளுக்கு தரமான விதைகள் மற்றும் மானிய விலை உரங்கள் இலவச விநியோகம். பயறு மற்றும் எண்ணெய் வித்துக்களுக்கான விதை மினிகிட்கள்.",
        "eligibility": "Small and marginal farmers in Tamil Nadu, particularly during sowing seasons.",
        "eligibility_ta": "தமிழ்நாட்டில் உள்ள சிறு மற்றும் குறு விவசாயிகள், குறிப்பாக விதைப்பு காலங்களில்.",
        "documents": "Aadhaar Card, Land Records, Farmer ID",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், விவசாயி அடையாள அட்டை",
        "link": "https://www.tn.gov.in",
        "icon": "🌰",
        "is_featured": False,
        "deadline": "",
    },
    {
        "id": "tn-women-farmer",
        "name": "Women Farmers Empowerment Scheme",
        "name_ta": "பெண் விவசாயிகள் மேம்பாட்டு திட்டம்",
        "category": "tn_finance",
        "category_en": "Tamil Nadu Government Financial",
        "category_ta": "தமிழ்நாடு அரசு நிதி திட்டங்கள்",
        "department": "Tamil Nadu Department of Agriculture",
        "department_ta": "தமிழ்நாடு வேளாண் துறை",
        "benefits": "Special financial assistance, training, and resources for women farmers. Priority in subsidy schemes and skill development programs.",
        "benefits_ta": "பெண் விவசாயிகளுக்கு சிறப்பு நிதி உதவி, பயிற்சி மற்றும் வளங்கள். மானிய திட்டங்கள் மற்றும் திறன் மேம்பாட்டு திட்டங்களில் முன்னுரிமை.",
        "eligibility": "Women farmers and women-headed farming families in Tamil Nadu.",
        "eligibility_ta": "தமிழ்நாட்டில் உள்ள பெண் விவசாயிகள் மற்றும் பெண் தலைமையிலான விவசாய குடும்பங்கள்.",
        "documents": "Aadhaar Card, Land Records, Women Farmer Certificate, Bank Account",
        "documents_ta": "ஆதார் அட்டை, நில ஆவணங்கள், பெண் விவசாயி சான்றிதழ், வங்கி கணக்கு",
        "link": "https://www.tn.gov.in",
        "icon": "👩‍🌾",
        "is_featured": False,
        "deadline": "",
    },
]

CATEGORIES = [
    {"id": "central_agri", "en": "Central Government Agriculture", "ta": "मத்திய அரசு வேளாண் திட்டங்கள்", "icon": "🇮🇳"},
    {"id": "central_finance", "en": "Central Government Financial", "ta": "मத்திய அரசு நிதி திட்டங்கள்", "icon": "🏛️"},
    {"id": "tn_agri", "en": "Tamil Nadu Government Agriculture", "ta": "தமிழ்நாடு அரசு வேளாண் திட்டங்கள்", "icon": "🏛️"},
    {"id": "tn_finance", "en": "Tamil Nadu Government Financial", "ta": "தமிழ்நாடு அரசு நிதி திட்டங்கள்", "icon": "💵"},
]

FAQS = [
    {
        "q": "How do I apply for PM-KISAN?",
        "q_ta": "PM-KISAN-க்கு எப்படி விண்ணப்பிப்பது?",
        "a": "Visit pmkisan.gov.in, click on 'New Farmer Registration', enter your Aadhaar number and bank details. Alternatively, visit your nearest Common Service Centre (CSC) or agriculture office.",
        "a_ta": "pmkisan.gov.in-ஐ பார்வையிடவும், 'புதிய விவசாயி பதிவு' என்பதைக் கிளிக் செய்து, உங்கள் ஆதார் எண் மற்றும் வங்கி விவரங்களை உள்ளிடவும். மாற்றாக, அருகிலுள்ள பொது சேவை மையம் (CSC) அல்லது வேளாண் அலுவலகத்தை அணுகவும்.",
    },
    {
        "q": "What documents are needed for crop insurance?",
        "q_ta": "பயிர் காப்பீட்டுக்கு என்ன ஆவணங்கள் தேவை?",
        "a": "Aadhaar Card, land records (patta/chitta), bank account details, crop details (acreage, crop type, season), and loan documents if applicable.",
        "a_ta": "ஆதார் அட்டை, நில ஆவணங்கள் (பட்டா/சிட்டா), வங்கி கணக்கு விவரங்கள், பயிர் விவரங்கள் (ஏக்கர், பயிர் வகை, பருவம்), மற்றும் கடன் ஆவணங்கள் (பொருந்தினால்).",
    },
    {
        "q": "How can I check my soil health card?",
        "q_ta": "என் மண் ஆரோக்கிய அட்டையை எப்படி பார்ப்பது?",
        "a": "Visit soilhealth.dac.gov.in, click on 'Farmer Corner', enter your soil health card number or mobile number. You can also get a free soil test at your nearest agriculture department office.",
        "a_ta": "soilhealth.dac.gov.in-ஐ பார்வையிடவும், 'விவசாயி மூலை' என்பதைக் கிளிக் செய்து, உங்கள் மண் ஆரோக்கிய அட்டை எண் அல்லது கைப்பேசி எண்ணை உள்ளிடவும். அருகிலுள்ள வேளாண் துறை அலுவலகத்தில் இலவச மண் பரிசோதனையும் பெறலாம்.",
    },
    {
        "q": "Is there a pension scheme for farmers?",
        "q_ta": "விவசாயிகளுக்கு ஓய்வூதிய திட்டம் உள்ளதா?",
        "a": "Yes, PM-KMY (Pradhan Mantri Kisan Maan Dhan Yojana) provides monthly pension of Rs. 3000 after 60 years. Farmers aged 18-40 can enroll through Common Service Centres or PM-KISAN portal.",
        "a_ta": "ஆம், PM-KMY (பிரதமர் கிசான் மான்தன் திட்டம்) 60 வயதுக்குப் பிறகு மாதம் ரூ. 3000 ஓய்வூதியம் வழங்குகிறது. 18-40 வயதுடைய விவசாயிகள் பொது சேவை மையங்கள் அல்லது PM-KISAN போர்டல் மூலம் சேரலாம்.",
    },
    {
        "q": "How to get free electricity for farming in TN?",
        "q_ta": "தமிழ்நாட்டில் விவசாயத்திற்கு இலவச மின்சாரம் எப்படி பெறுவது?",
        "a": "Apply at your nearest TNEB office with land records, pump set details, and Aadhaar. The scheme provides free electricity for agricultural pump sets up to prescribed horsepower limits.",
        "a_ta": "நில ஆவணங்கள், பம்ப் செட் விவரங்கள் மற்றும் ஆதாருடன் அருகிலுள்ள TNEB அலுவலகத்தில் விண்ணப்பிக்கவும். இந்த திட்டம் நிர்ணயிக்கப்பட்ட குதிரைத்திறன் வரை இலவச மின்சாரம் வழங்குகிறது.",
    },
    {
        "q": "What subsidy is available for drip irrigation?",
        "q_ta": "சொட்டு நீர்ப்பாசனத்திற்கு என்ன மானியம் உள்ளது?",
        "a": "Under the TN Micro Irrigation Scheme, farmers can get up to 80% subsidy on drip and sprinkler systems. Apply through your district agriculture department office.",
        "a_ta": "தமிழ்நாடு சிறு நீர்ப்பாசன திட்டத்தின் கீழ், விவசாயிகள் சொட்டு மற்றும் தெளிப்பு முறைகளுக்கு 80% வரை மானியம் பெறலாம். உங்கள் மாவட்ட வேளாண் துறை அலுவலகம் மூலம் விண்ணப்பிக்கவும்.",
    },
]


class SchemeService:
    def __init__(self):
        self._cache = {
            "data": SCHEMES,
            "ts": time.time()
        }
        self.cache_ttl = 3600

    def _refresh_if_needed(self):
        if time.time() - self._cache["ts"] > self.cache_ttl:
            self._cache["data"] = SCHEMES
            self._cache["ts"] = time.time()

    def get_all_schemes(self):
        self._refresh_if_needed()
        return self._cache["data"]

    def get_by_id(self, scheme_id):
        self._refresh_if_needed()
        for s in self._cache["data"]:
            if s["id"] == scheme_id:
                return s
        return None

    def get_by_category(self, category_id):
        self._refresh_if_needed()
        return [s for s in self._cache["data"] if s["category"] == category_id]

    def search(self, query):
        self._refresh_if_needed()
        q = query.strip().lower()
        if not q:
            return self._cache["data"]
        results = []
        for s in self._cache["data"]:
            if (q in s["name"].lower() or
                q in s["name_ta"].lower() or
                q in s["benefits"].lower() or
                q in s["benefits_ta"].lower() or
                q in s["eligibility"].lower() or
                q in s["eligibility_ta"].lower() or
                q in s["department"].lower()):
                results.append(s)
        return results

    def get_featured(self):
        self._refresh_if_needed()
        return [s for s in self._cache["data"] if s.get("is_featured")]

    def get_categories(self):
        return CATEGORIES

    def get_faqs(self):
        return FAQS
